nelmio_api_doc:
     documentation:
         info:
             title: StudyOn.Billing
             description: Проект StudyOn.Billing
             version: 1.0.0
     areas: 
         path_patterns:
             - ^/api/v1(?!/doc$)