<?php

namespace Container22V1M6z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KuajCdMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KuajCdM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KuajCdM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
            'tokenGenerator' => ['privates', 'App\\Security\\JwtTokenGenerator', 'getJwtTokenGeneratorService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'serializer' => '?',
            'tokenGenerator' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'validator' => '?',
        ]);
    }
}
