parameters:

services:

    _defaults:
        autowire: true   
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Security\JwtTokenGenerator:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
        tags:
            
    App\Security\TokenGeneratorInterface: '@App\Security\JwtTokenGenerator'