<?php

namespace ContainerHea7iTn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJwtTokenGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\JwtTokenGenerator' shared autowired service.
     *
     * @return \App\Security\JwtTokenGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/TokenGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/JwtTokenGenerator.php';

        return $container->privates['App\\Security\\JwtTokenGenerator'] = new \App\Security\JwtTokenGenerator(($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')));
    }
}
