<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1X4ZHfx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1X4ZHfx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1X4ZHfx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1X4ZHfx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1X4ZHfx\App_KernelDevDebugContainer([
    'container.build_hash' => '1X4ZHfx',
    'container.build_id' => '87e55682',
    'container.build_time' => 1710779236,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1X4ZHfx');
