<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAa9QsCh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAa9QsCh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAa9QsCh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAa9QsCh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAa9QsCh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Aa9QsCh',
    'container.build_id' => 'ef58be25',
    'container.build_time' => 1710830808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAa9QsCh');
