<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHea7iTn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHea7iTn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHea7iTn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHea7iTn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHea7iTn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hea7iTn',
    'container.build_id' => 'df7118e2',
    'container.build_time' => 1710785999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHea7iTn');
